name: Docker-minimal

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  docker-minimal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image minimal example
        run: |
          docker build -t radixgraph-exp ./minimal-example
      
      - name: Run experiments with docker image
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/minimal-example:/workspace/minimal-example \
            radixgraph-exp \
            /workspace/minimal-example/run_minimal.sh